# Node 이미지 사용
FROM node:20-alpine

# 빌드 의존성 설치
RUN apk add --no-cache python3 g++ make
# 작업 디렉토리 생성
WORKDIR /usr/src/app

# package.json 먼저 복사 (캐시 활용)
COPY package*.json ./



# 의존성 설치
RUN npm install
RUN npm rebuild bcrypt --build-from-source
# 나머지 소스 복사
COPY . .
RUN npm run build

# NestJS 기본 포트
EXPOSE 3000 9229

# 개발용 실행 (watch 모드)
CMD ["node","dist/src/main.js"]